In [1]:
import numpy as np

# Create a sample array
data = np.random.randint(0, 100, size=(4, 4))

# Display the original array
print("Original Array:")
print(data)

# Set values below 40 to 0 and everything else to 255
processed_data = np.where(data < 40, 0, 255)

# Display the modified array
print("\nModified Array:")
print(processed_data)


Original Array:
[[93 28  8 23]
 [34 87 77 97]
 [59 13 95 19]
 [36  3  6  8]]

Modified Array:
[[255   0   0   0]
 [  0 255 255 255]
 [255   0 255   0]
 [  0   0   0   0]]


In [2]:
print("hello")

hello


In [2]:
import numpy as np
np.radians(60)

1.0471975511965976

In [5]:
import cv2
image = cv2.imread('/mnt/d/Codes/Experiments/cv_project_colab_december/final_project/cad_images/cad2.png')
image.shape

(1684, 2382, 3)